name: .NET Core

on:
  push:
    branches: [ root ]
  pull_request:
    branches: [ root ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test and Coverage
      run: dotnet test src/Floatingman.Common.xUnit/Floatingman.Common.xUnit.csproj  /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcovun: dotnet test --no-restore --verbosity normal
